/*
 * Decompiled with CFR 0_115.
 */
package com.lowagie.text.xml.simpleparser;

import com.lowagie.text.Chunk;
import com.lowagie.text.Font;
import java.awt.Color;
import java.util.HashMap;

public class EntitiesToSymbol {
    public static final HashMap map = new HashMap();

    public static Chunk get(String string, Font font) {
        char c = EntitiesToSymbol.getCorrespondingSymbol(string);
        if (c == '\u0000') {
            try {
                return new Chunk(String.valueOf((char)Integer.parseInt(string)), font);
            }
            catch (Exception var3_3) {
                return new Chunk(string, font);
            }
        }
        Font font2 = new Font(3, font.getSize(), font.getStyle(), font.getColor());
        return new Chunk(String.valueOf(c), font2);
    }

    public static char getCorrespondingSymbol(String string) {
        Character c = (Character)map.get(string);
        if (c == null) {
            return '\u0000';
        }
        return c.charValue();
    }

    static {
        map.put("169", new Character('\u00e3'));
        map.put("172", new Character('\u00d8'));
        map.put("174", new Character('\u00d2'));
        map.put("177", new Character('\u00b1'));
        map.put("215", new Character('\u00b4'));
        map.put("247", new Character('\u00b8'));
        map.put("8230", new Character('\u00bc'));
        map.put("8242", new Character('\u00a2'));
        map.put("8243", new Character('\u00b2'));
        map.put("8260", new Character('\u00a4'));
        map.put("8364", new Character('\u00f0'));
        map.put("8465", new Character('\u00c1'));
        map.put("8472", new Character('\u00c3'));
        map.put("8476", new Character('\u00c2'));
        map.put("8482", new Character('\u00d4'));
        map.put("8501", new Character('\u00c0'));
        map.put("8592", new Character('\u00ac'));
        map.put("8593", new Character('\u00ad'));
        map.put("8594", new Character('\u00ae'));
        map.put("8595", new Character('\u00af'));
        map.put("8596", new Character('\u00ab'));
        map.put("8629", new Character('\u00bf'));
        map.put("8656", new Character('\u00dc'));
        map.put("8657", new Character('\u00dd'));
        map.put("8658", new Character('\u00de'));
        map.put("8659", new Character('\u00df'));
        map.put("8660", new Character('\u00db'));
        map.put("8704", new Character('\"'));
        map.put("8706", new Character('\u00b6'));
        map.put("8707", new Character('$'));
        map.put("8709", new Character('\u00c6'));
        map.put("8711", new Character('\u00d1'));
        map.put("8712", new Character('\u00ce'));
        map.put("8713", new Character('\u00cf'));
        map.put("8717", new Character('\''));
        map.put("8719", new Character('\u00d5'));
        map.put("8721", new Character('\u00e5'));
        map.put("8722", new Character('-'));
        map.put("8727", new Character('*'));
        map.put("8729", new Character('\u00b7'));
        map.put("8730", new Character('\u00d6'));
        map.put("8733", new Character('\u00b5'));
        map.put("8734", new Character('\u00a5'));
        map.put("8736", new Character('\u00d0'));
        map.put("8743", new Character('\u00d9'));
        map.put("8744", new Character('\u00da'));
        map.put("8745", new Character('\u00c7'));
        map.put("8746", new Character('\u00c8'));
        map.put("8747", new Character('\u00f2'));
        map.put("8756", new Character('\\'));
        map.put("8764", new Character('~'));
        map.put("8773", new Character('@'));
        map.put("8776", new Character('\u00bb'));
        map.put("8800", new Character('\u00b9'));
        map.put("8801", new Character('\u00ba'));
        map.put("8804", new Character('\u00a3'));
        map.put("8805", new Character('\u00b3'));
        map.put("8834", new Character('\u00cc'));
        map.put("8835", new Character('\u00c9'));
        map.put("8836", new Character('\u00cb'));
        map.put("8838", new Character('\u00cd'));
        map.put("8839", new Character('\u00ca'));
        map.put("8853", new Character('\u00c5'));
        map.put("8855", new Character('\u00c4'));
        map.put("8869", new Character('^'));
        map.put("8901", new Character('\u00d7'));
        map.put("8992", new Character('\u00f3'));
        map.put("8993", new Character('\u00f5'));
        map.put("9001", new Character('\u00e1'));
        map.put("9002", new Character('\u00f1'));
        map.put("913", new Character('A'));
        map.put("914", new Character('B'));
        map.put("915", new Character('G'));
        map.put("916", new Character('D'));
        map.put("917", new Character('E'));
        map.put("918", new Character('Z'));
        map.put("919", new Character('H'));
        map.put("920", new Character('Q'));
        map.put("921", new Character('I'));
        map.put("922", new Character('K'));
        map.put("923", new Character('L'));
        map.put("924", new Character('M'));
        map.put("925", new Character('N'));
        map.put("926", new Character('X'));
        map.put("927", new Character('O'));
        map.put("928", new Character('P'));
        map.put("929", new Character('R'));
        map.put("931", new Character('S'));
        map.put("932", new Character('T'));
        map.put("933", new Character('U'));
        map.put("934", new Character('F'));
        map.put("935", new Character('C'));
        map.put("936", new Character('Y'));
        map.put("937", new Character('W'));
        map.put("945", new Character('a'));
        map.put("946", new Character('b'));
        map.put("947", new Character('g'));
        map.put("948", new Character('d'));
        map.put("949", new Character('e'));
        map.put("950", new Character('z'));
        map.put("951", new Character('h'));
        map.put("952", new Character('q'));
        map.put("953", new Character('i'));
        map.put("954", new Character('k'));
        map.put("955", new Character('l'));
        map.put("956", new Character('m'));
        map.put("957", new Character('n'));
        map.put("958", new Character('x'));
        map.put("959", new Character('o'));
        map.put("960", new Character('p'));
        map.put("961", new Character('r'));
        map.put("962", new Character('V'));
        map.put("963", new Character('s'));
        map.put("964", new Character('t'));
        map.put("965", new Character('u'));
        map.put("966", new Character('f'));
        map.put("967", new Character('c'));
        map.put("9674", new Character('\u00e0'));
        map.put("968", new Character('y'));
        map.put("969", new Character('w'));
        map.put("977", new Character('J'));
        map.put("978", new Character('\u00a1'));
        map.put("981", new Character('j'));
        map.put("982", new Character('v'));
        map.put("9824", new Character('\u00aa'));
        map.put("9827", new Character('\u00a7'));
        map.put("9829", new Character('\u00a9'));
        map.put("9830", new Character('\u00a8'));
        map.put("Alpha", new Character('A'));
        map.put("Beta", new Character('B'));
        map.put("Chi", new Character('C'));
        map.put("Delta", new Character('D'));
        map.put("Epsilon", new Character('E'));
        map.put("Eta", new Character('H'));
        map.put("Gamma", new Character('G'));
        map.put("Iota", new Character('I'));
        map.put("Kappa", new Character('K'));
        map.put("Lambda", new Character('L'));
        map.put("Mu", new Character('M'));
        map.put("Nu", new Character('N'));
        map.put("Omega", new Character('W'));
        map.put("Omicron", new Character('O'));
        map.put("Phi", new Character('F'));
        map.put("Pi", new Character('P'));
        map.put("Prime", new Character('\u00b2'));
        map.put("Psi", new Character('Y'));
        map.put("Rho", new Character('R'));
        map.put("Sigma", new Character('S'));
        map.put("Tau", new Character('T'));
        map.put("Theta", new Character('Q'));
        map.put("Upsilon", new Character('U'));
        map.put("Xi", new Character('X'));
        map.put("Zeta", new Character('Z'));
        map.put("alefsym", new Character('\u00c0'));
        map.put("alpha", new Character('a'));
        map.put("and", new Character('\u00d9'));
        map.put("ang", new Character('\u00d0'));
        map.put("asymp", new Character('\u00bb'));
        map.put("beta", new Character('b'));
        map.put("cap", new Character('\u00c7'));
        map.put("chi", new Character('c'));
        map.put("clubs", new Character('\u00a7'));
        map.put("cong", new Character('@'));
        map.put("copy", new Character('\u00d3'));
        map.put("crarr", new Character('\u00bf'));
        map.put("cup", new Character('\u00c8'));
        map.put("dArr", new Character('\u00df'));
        map.put("darr", new Character('\u00af'));
        map.put("delta", new Character('d'));
        map.put("diams", new Character('\u00a8'));
        map.put("divide", new Character('\u00b8'));
        map.put("empty", new Character('\u00c6'));
        map.put("epsilon", new Character('e'));
        map.put("equiv", new Character('\u00ba'));
        map.put("eta", new Character('h'));
        map.put("euro", new Character('\u00f0'));
        map.put("exist", new Character('$'));
        map.put("forall", new Character('\"'));
        map.put("frasl", new Character('\u00a4'));
        map.put("gamma", new Character('g'));
        map.put("ge", new Character('\u00b3'));
        map.put("hArr", new Character('\u00db'));
        map.put("harr", new Character('\u00ab'));
        map.put("hearts", new Character('\u00a9'));
        map.put("hellip", new Character('\u00bc'));
        map.put("horizontal arrow extender", new Character('\u00be'));
        map.put("image", new Character('\u00c1'));
        map.put("infin", new Character('\u00a5'));
        map.put("int", new Character('\u00f2'));
        map.put("iota", new Character('i'));
        map.put("isin", new Character('\u00ce'));
        map.put("kappa", new Character('k'));
        map.put("lArr", new Character('\u00dc'));
        map.put("lambda", new Character('l'));
        map.put("lang", new Character('\u00e1'));
        map.put("large brace extender", new Character('\u00ef'));
        map.put("large integral extender", new Character('\u00f4'));
        map.put("large left brace (bottom)", new Character('\u00ee'));
        map.put("large left brace (middle)", new Character('\u00ed'));
        map.put("large left brace (top)", new Character('\u00ec'));
        map.put("large left bracket (bottom)", new Character('\u00eb'));
        map.put("large left bracket (extender)", new Character('\u00ea'));
        map.put("large left bracket (top)", new Character('\u00e9'));
        map.put("large left parenthesis (bottom)", new Character('\u00e8'));
        map.put("large left parenthesis (extender)", new Character('\u00e7'));
        map.put("large left parenthesis (top)", new Character('\u00e6'));
        map.put("large right brace (bottom)", new Character('\u00fe'));
        map.put("large right brace (middle)", new Character('\u00fd'));
        map.put("large right brace (top)", new Character('\u00fc'));
        map.put("large right bracket (bottom)", new Character('\u00fb'));
        map.put("large right bracket (extender)", new Character('\u00fa'));
        map.put("large right bracket (top)", new Character('\u00f9'));
        map.put("large right parenthesis (bottom)", new Character('\u00f8'));
        map.put("large right parenthesis (extender)", new Character('\u00f7'));
        map.put("large right parenthesis (top)", new Character('\u00f6'));
        map.put("larr", new Character('\u00ac'));
        map.put("le", new Character('\u00a3'));
        map.put("lowast", new Character('*'));
        map.put("loz", new Character('\u00e0'));
        map.put("minus", new Character('-'));
        map.put("mu", new Character('m'));
        map.put("nabla", new Character('\u00d1'));
        map.put("ne", new Character('\u00b9'));
        map.put("not", new Character('\u00d8'));
        map.put("notin", new Character('\u00cf'));
        map.put("nsub", new Character('\u00cb'));
        map.put("nu", new Character('n'));
        map.put("omega", new Character('w'));
        map.put("omicron", new Character('o'));
        map.put("oplus", new Character('\u00c5'));
        map.put("or", new Character('\u00da'));
        map.put("otimes", new Character('\u00c4'));
        map.put("part", new Character('\u00b6'));
        map.put("perp", new Character('^'));
        map.put("phi", new Character('f'));
        map.put("pi", new Character('p'));
        map.put("piv", new Character('v'));
        map.put("plusmn", new Character('\u00b1'));
        map.put("prime", new Character('\u00a2'));
        map.put("prod", new Character('\u00d5'));
        map.put("prop", new Character('\u00b5'));
        map.put("psi", new Character('y'));
        map.put("rArr", new Character('\u00de'));
        map.put("radic", new Character('\u00d6'));
        map.put("radical extender", new Character('`'));
        map.put("rang", new Character('\u00f1'));
        map.put("rarr", new Character('\u00ae'));
        map.put("real", new Character('\u00c2'));
        map.put("reg", new Character('\u00d2'));
        map.put("rho", new Character('r'));
        map.put("sdot", new Character('\u00d7'));
        map.put("sigma", new Character('s'));
        map.put("sigmaf", new Character('V'));
        map.put("sim", new Character('~'));
        map.put("spades", new Character('\u00aa'));
        map.put("sub", new Character('\u00cc'));
        map.put("sube", new Character('\u00cd'));
        map.put("sum", new Character('\u00e5'));
        map.put("sup", new Character('\u00c9'));
        map.put("supe", new Character('\u00ca'));
        map.put("tau", new Character('t'));
        map.put("there4", new Character('\\'));
        map.put("theta", new Character('q'));
        map.put("thetasym", new Character('J'));
        map.put("times", new Character('\u00b4'));
        map.put("trade", new Character('\u00d4'));
        map.put("uArr", new Character('\u00dd'));
        map.put("uarr", new Character('\u00ad'));
        map.put("upsih", new Character('\u00a1'));
        map.put("upsilon", new Character('u'));
        map.put("vertical arrow extender", new Character('\u00bd'));
        map.put("weierp", new Character('\u00c3'));
        map.put("xi", new Character('x'));
        map.put("zeta", new Character('z'));
    }
}

